version: '2'
services:
  api:
    image: 'scprdev/resound-api'
    ports: ['3000:3000']
  web:
    image: 'scprdev/resound-store-manage'
    ports: ['80:80']
    environment:
      - API_URL=$API_URL
